"""Initial migration UsersORMs

Revision ID: a69de35679bb
Revises: 
Create Date: 2025-04-01 19:51:58.302308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69de35679bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'client', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('personas_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lastname_1', sa.String(length=50), nullable=False),
    sa.Column('lastname_2', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('nationality', sa.Enum('mexicana', 'extranjera', name='nacionalidad_enum'), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personas_fisicas_id'), 'personas_fisicas', ['id'], unique=False)
    op.create_table('personas_morales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_legal_name', sa.String(length=50), nullable=False),
    sa.Column('constitution_date', sa.DateTime(), nullable=False),
    sa.Column('activity', sa.String(length=50), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('lastname_1', sa.String(length=50), nullable=False),
    sa.Column('lastname_2', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personas_morales_id'), 'personas_morales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_morales_id'), table_name='personas_morales')
    op.drop_table('personas_morales')
    op.drop_index(op.f('ix_personas_fisicas_id'), table_name='personas_fisicas')
    op.drop_table('personas_fisicas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
